# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
#
# Translators:
msgid ""
msgstr ""
"Project-Id-Version: pykolab\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2013-01-12 11:17+0000\n"
"PO-Revision-Date: 2012-08-11 13:02+0000\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: af\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"

#: ../bin/kolab_smtp_access_policy.py:206
#, python-format
msgid "Adding policy request to instance %s"
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:446
msgid "Unauthorized access not allowed"
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:475
#: ../bin/kolab_smtp_access_policy.py:657
msgid "Could not find recipient"
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:494
#: ../bin/kolab_smtp_access_policy.py:594
#, python-format
msgid "Could not find envelope sender user %s"
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:537
#, python-format
msgid "Obtained authenticated user details for %r: %r"
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:616
#, python-format
msgid "%s is unauthorized to send on behalf of %s"
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:626
#, python-format
msgid "User %s attempted to use envelope sender address %s "
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:681
#: ../bin/kolab_smtp_access_policy.py:692
#, python-format
msgid "Found user %s to be a delegate user of %s"
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:716
#, python-format
msgid "Verifying authenticated sender '%(sender)s' with "
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:721
#, python-format
msgid "Verifying unauthenticated sender '%(sender)s' "
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:738
#, python-format
msgid "Reproducing verify_recipient(%s, %s) from "
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:760
#, python-format
msgid "Using authentication domain %s instead of %s"
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:770
#, python-format
msgid "Domain %s is a primary domain"
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:778
#, python-format
msgid "Checking the recipient for domain %s that is not "
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:794
msgid "This recipient address is related to multiple "
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:803
#, python-format
msgid "Recipient address %r not found. Allowing since "
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:831
msgid "Invalid recipient"
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:842
msgid "Could not find this user, accepting"
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:905
#: ../bin/kolab_smtp_access_policy.py:958
#, python-format
msgid "Sender %s is not allowed to send to "
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:945
#, python-format
msgid "Reproducing verify_sender(%r) from cache, "
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:974
msgid "Sender uses unauthorized envelope sender address"
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:991
msgid "Could not verify sender"
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:998
msgid "Verifying whether sender is allowed to send to "
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:1012
#, python-format
msgid "Result is %r"
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:1017
msgid "No recipient policy restrictions exist for this sender"
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:1026
msgid "Found a recipient policy to apply for this sender."
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:1041
#, python-format
msgid "Sender %s not allowed to send to recipient "
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:1063
msgid "Cleaning up the cache"
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:1085
msgid ""
"The 'uri' setting in the kolab_smtp_access_policy section is soon going to "
"be deprecated in favor of 'cache_uri'"
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:1101
#, python-format
msgid "Operational Error in caching: %s"
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:1152
#, python-format
msgid "Caching the policy result with timestamp %d"
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:1229
#, python-format
msgid "Returning action DEFER_IF_PERMIT: %s"
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:1234
#, python-format
msgid "Returning action DUNNO: %s"
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:1239
#, python-format
msgid "Returning action HOLD: %s"
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:1244
#, python-format
msgid "Returning action PERMIT: %s"
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:1249
#, python-format
msgid "Returning action REJECT: %s"
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:1298
msgid "Starting to loop for new request"
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:1305
msgid "Timeout for policy request reading exceeded"
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:1311
msgid "End of current request"
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:1315
#, python-format
msgid "Getting line: %s"
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:1319
msgid "Returning request"
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:1348
msgid "Access Policy Options"
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:1355
msgid "SMTP Policy request timeout."
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:1361
msgid "Verify the recipient access policy."
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:1367
msgid "Verify the sender access policy."
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:1373
msgid "Allow unauthenticated senders."
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:1385
#, python-format
msgid "Got request instance %s"
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:1394
#, python-format
msgid "Request instance %s is in state %s"
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:1402
#, python-format
msgid "Request instance %s is not yet in DATA state"
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:1414
#, python-format
msgid "Request instance %s reached DATA state"
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:1432
msgid "Sender access denied"
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:1434
msgid "Recipient access denied"
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:1436
msgid "No objections"
msgstr ""

#: ../conf.py:37 ../kolab.py:34 ../saslauthd.py:33
msgid "Cannot load pykolab/logger.py:"
msgstr ""

#: ../kolabd/__init__.py:49 ../saslauthd/__init__.py:48
#: ../wallace/__init__.py:66
msgid "Daemon Options"
msgstr ""

#: ../kolabd/__init__.py:56 ../saslauthd/__init__.py:55
#: ../wallace/__init__.py:73
msgid "Fork to the background."
msgstr ""

#: ../kolabd/__init__.py:65 ../saslauthd/__init__.py:64
#: ../wallace/__init__.py:99
msgid "Path to the PID file to use."
msgstr ""

#: ../kolabd/__init__.py:74 ../saslauthd/__init__.py:73
#: ../wallace/__init__.py:116
msgid "Run as user USERNAME"
msgstr ""

#: ../kolabd/__init__.py:84 ../saslauthd/__init__.py:83
#: ../wallace/__init__.py:90
msgid "Run as group GROUPNAME"
msgstr ""

#: ../kolabd/__init__.py:122 ../pykolab/utils.py:180
#: ../wallace/__init__.py:297
#, python-format
msgid "Group %s does not exist"
msgstr ""

#: ../kolabd/__init__.py:131 ../wallace/__init__.py:306
#, python-format
msgid "Switching real and effective group id to %d"
msgstr ""

#: ../kolabd/__init__.py:153 ../pykolab/utils.py:204
#: ../wallace/__init__.py:328
#, python-format
msgid "User %s does not exist"
msgstr ""

#: ../kolabd/__init__.py:163 ../wallace/__init__.py:338
#, python-format
msgid "Switching real and effective user id to %d"
msgstr ""

#: ../kolabd/__init__.py:172 ../wallace/__init__.py:347
msgid "Could not change real and effective uid and/or gid"
msgstr ""

#: ../kolabd/__init__.py:192 ../saslauthd/__init__.py:122
#: ../wallace/__init__.py:367
msgid "Interrupted by user"
msgstr ""

#: ../kolabd/__init__.py:197 ../kolabd/__init__.py:208
#: ../wallace/__init__.py:371 ../wallace/__init__.py:381
msgid "Traceback occurred, please report a "
msgstr ""

#: ../kolabd/__init__.py:203 ../saslauthd/__init__.py:130
#: ../wallace/__init__.py:377
#, python-format
msgid "Type Error: %s"
msgstr ""

#: ../kolabd/__init__.py:223 ../pykolab/auth/ldap/__init__.py:1623
#: ../pykolab/cli/cmd_sync.py:36
msgid "Listing domains..."
msgstr ""

#: ../kolabd/__init__.py:260
#, python-format
msgid "added domains: %r, removed domains: %r"
msgstr ""

#: ../kolabd/process.py:48
#, python-format
msgid "Error in process %r, terminating: %r"
msgstr ""

#: ../kolabd.py:31 ../setup-kolab.py:36 ../wallace.py:31
msgid "Cannot load pykolab/constants.py:"
msgstr ""

#: ../pykolab/auth/__init__.py:94
#, python-format
msgid "Called for domain %r"
msgstr ""

#: ../pykolab/auth/__init__.py:107 ../pykolab/auth/__init__.py:116
#, python-format
msgid "Using section %s and domain %s"
msgstr ""

#: ../pykolab/auth/__init__.py:121
#, python-format
msgid "Connecting to Authentication backend for domain %s"
msgstr ""

#: ../pykolab/auth/__init__.py:132
#, python-format
msgid "Section %s has no option 'auth_mechanism'"
msgstr ""

#: ../pykolab/auth/__init__.py:139
#, python-format
msgid "Section %s has auth_mechanism: %r"
msgstr ""

#: ../pykolab/auth/__init__.py:148 ../pykolab/auth/__init__.py:157
msgid "Starting LDAP..."
msgstr ""

#: ../pykolab/auth/ldap/cache.py:112
#, python-format
msgid "Inserting cache entry %r"
msgstr ""

#: ../pykolab/auth/ldap/cache.py:129
#, python-format
msgid "Updating timestamp for cache entry %r"
msgstr ""

#: ../pykolab/auth/ldap/cache.py:136
#, python-format
msgid "Updating result_attribute for cache entry %r"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:51
msgid "Python LDAP library does not support persistent search"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:142
#, python-format
msgid "Attempting to authenticate user %s in realm %s"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:184
#, python-format
msgid "Binding with user_dn %s and password %s"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:194
#, python-format
msgid "Failed to authenticate as user %s"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:211
msgid "Connecting to LDAP..."
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:215
#, python-format
msgid "Attempting to use LDAP URI %s"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:363
#, python-format
msgid "Finding recipient with filter %r"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:431
#, python-format
msgid "Finding resource with filter %r"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:454
#, python-format
msgid "Using timestamp %r"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:486
#, python-format
msgid "Applying recipient policy to %r"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:503
#, python-format
msgid "Using mail attributes: %r, with primary %r and "
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:514
#, python-format
msgid "key %r not in entry"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:516
#, python-format
msgid "key %r is the prim. mail attr."
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:518
msgid "prim. mail pol. is not empty"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:521
#, python-format
msgid "key %r is the sec. mail attr."
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:523
msgid "sec. mail pol. is not empty"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:527 ../pykolab/auth/ldap/__init__.py:541
#, python-format
msgid "Attributes %r are not yet available for entry %r"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:577
#, python-format
msgid "No results for mail address %s found"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:588
#, python-format
msgid "1 result for address %s found, verifying"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:598
#, python-format
msgid "Too bad, primary email address %s "
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:609 ../pykolab/auth/ldap/__init__.py:698
msgid "Address assigned to us"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:664
#, python-format
msgid "No results for address %s found"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:675
#, python-format
msgid "1 result for address %s found, "
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:686
msgid "Too bad, secondary email "
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:713
msgid "Recipient policy composed the following set of secondary "
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:724
#, python-format
msgid "Secondary mail addresses that we want is not None: %r"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:735
msgid "Avoiding the duplication of the primary mail "
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:746
#, python-format
msgid "Entry is getting secondary mail addresses: %r"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:754
msgid "Entry did not have any secondary mail "
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:780
#, python-format
msgid "Entry modifications list: %r"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:800
#, python-format
msgid "Setting entry attribute %r to %r for %r"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:836
#, python-format
msgid "Could not update dn %r"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:849
#, python-format
msgid "Using filter %r"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:887
#, python-format
msgid "About to consider the user quota for %r (used: %r, "
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:953
msgid "Invalid bind credentials"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:1248 ../pykolab/auth/ldap/__init__.py:1372
#, python-format
msgid "Result from recipient policy: %r"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:1417
#, python-format
msgid "Kolab user %s does not have a result attribute %r"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:1559
#, python-format
msgid "Finding domain root dn for domain %s"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:1647
msgid "Authentication database DOWN"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:1731 ../pykolab/auth/ldap/__init__.py:1766
#, python-format
msgid "Entry type: %s"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:1854
msgid "LDAP Search Result Data Entry:"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:1870
msgid "Entry Change Notification attributes:"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:1875
#, python-format
msgid "Change Type: %r (%r)"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:1883
#, python-format
msgid "Previous DN: %r"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:1938
#, python-format
msgid "Object %s searched no longer exists"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:1948
#, python-format
msgid "%d results..."
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:2051
#, python-format
msgid "Searching with filter %r"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:2095
#, python-format
msgid "Checking for support for %s on %s"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:2114
#, python-format
msgid "Found support for %s"
msgstr ""

#: ../pykolab/cli/cmd_add_domain.py:36 ../pykolab/cli/cmd_create_mailbox.py:36
#: ../pykolab/cli/cmd_export_mailbox.py:33
#: ../pykolab/cli/cmd_list_mailboxes.py:39
#: ../pykolab/cli/cmd_list_mailbox_metadata.py:37
#: ../pykolab/cli/cmd_set_mailbox_metadata.py:37
msgid "CLI Options"
msgstr ""

#: ../pykolab/cli/cmd_add_domain.py:42
msgid "Add domain as alias for DOMAIN"
msgstr ""

#: ../pykolab/cli/cmd_add_domain.py:47
msgid "Add a new domain or domain alias."
msgstr ""

#: ../pykolab/cli/cmd_add_domain.py:55
msgid "Could not find credentials with sufficient permissions"
msgstr ""

#: ../pykolab/cli/cmd_add_domain.py:80 ../pykolab/wap_client/__init__.py:113
msgid "Invalid parent domain"
msgstr ""

#: ../pykolab/cli/cmd_add_domain.py:86
msgid "Domain name"
msgstr ""

#: ../pykolab/cli/cmd_create_mailbox.py:42
msgid "Set metadata for folder to ANNOTATION=VALUE"
msgstr ""

#: ../pykolab/cli/cmd_create_mailbox.py:52
msgid "Invalid argument"
msgstr ""

#: ../pykolab/cli/cmd_create_mailbox.py:60
msgid "Invalid argument for metadata"
msgstr ""

#: ../pykolab/cli/cmd_delete_mailbox_acl.py:45
#: ../pykolab/cli/cmd_delete_mailbox_acl.py:49
#: ../pykolab/cli/cmd_set_mailbox_acl.py:50
#: ../pykolab/cli/cmd_set_mailbox_acl.py:55
msgid "ACI Subject"
msgstr ""

#: ../pykolab/cli/cmd_delete_mailbox_acl.py:48
#: ../pykolab/cli/cmd_list_mailbox_acls.py:43
#: ../pykolab/cli/cmd_list_mailbox_metadata.py:54
#: ../pykolab/cli/cmd_set_mailbox_acl.py:54
#: ../pykolab/cli/cmd_set_mailbox_metadata.py:65
msgid "Folder name"
msgstr ""

#: ../pykolab/cli/cmd_delete_mailbox_acl.py:60
#: ../pykolab/cli/cmd_list_mailbox_acls.py:54
#: ../pykolab/cli/cmd_list_mailbox_metadata.py:80
#: ../pykolab/cli/cmd_set_mailbox_acl.py:67
#: ../pykolab/cli/cmd_set_mailbox_metadata.py:93
#, python-format
msgid "No such folder %r"
msgstr ""

#: ../pykolab/cli/cmd_delete_mailbox.py:46
msgid "No mailbox specified"
msgstr ""

#: ../pykolab/cli/cmd_export_mailbox.py:38
msgid "All folders this user has access to"
msgstr ""

#: ../pykolab/cli/cmd_export_mailbox.py:108
#, python-format
msgid "%s is not a directory"
msgstr ""

#: ../pykolab/cli/cmd_export_mailbox.py:118
#, python-format
msgid "ZIP file at %s.zip"
msgstr ""

#: ../pykolab/cli/cmd_export_mailbox.py:120
#, python-format
msgid "No directories found for user %s"
msgstr ""

#: ../pykolab/cli/cmd_list_mailboxes.py:44
msgid "Display raw IMAP UTF-7 folder names"
msgstr ""

#: ../pykolab/cli/cmd_list_mailboxes.py:75
#, python-format
msgid "Appending folder search for %r"
msgstr ""

#: ../pykolab/cli/cmd_list_mailbox_metadata.py:44
msgid "List annotations as user USER"
msgstr ""

#: ../pykolab/cli/cmd_list_quota.py:59 ../pykolab/cli/cmd_list_quota.py:71
#, python-format
msgid "The quota for folder %s is set to literally allow 0KB of storage."
msgstr ""

#: ../pykolab/cli/cmd_remove_mailaddress.py:49
msgid "Invalid or unqualified email address."
msgstr ""

#: ../pykolab/cli/cmd_remove_mailaddress.py:57
#, python-format
msgid "No recipient found for email address %r"
msgstr ""

#: ../pykolab/cli/cmd_remove_mailaddress.py:60
#, python-format
msgid "Found the following recipient(s): %r"
msgstr ""

#: ../pykolab/cli/cmd_remove_mailaddress.py:66
#, python-format
msgid "Using the following mail attributes: %r"
msgstr ""

#: ../pykolab/cli/cmd_remove_mailaddress.py:90
msgid "Found the following recipients:"
msgstr ""

#: ../pykolab/cli/cmd_rename_mailbox.py:48
msgid "No target mailbox name specified"
msgstr ""

#: ../pykolab/cli/cmd_rename_mailbox.py:50
msgid "No source mailbox name specified"
msgstr ""

#: ../pykolab/cli/cmd_rename_mailbox.py:62
#, python-format
msgid "Source folder %r does not exist"
msgstr ""

#: ../pykolab/cli/cmd_rename_mailbox.py:66
#, python-format
msgid "Target folder %r already exists"
msgstr ""

#: ../pykolab/cli/cmd_set_mailbox_acl.py:47
#: ../pykolab/cli/cmd_set_mailbox_acl.py:51
#: ../pykolab/cli/cmd_set_mailbox_acl.py:56
msgid "ACI Permissions"
msgstr ""

#: ../pykolab/cli/cmd_set_mailbox_metadata.py:44
msgid "Set annotation as user USER"
msgstr ""

#: ../pykolab/cli/cmd_set_mailbox_metadata.py:58
#: ../pykolab/cli/cmd_set_mailbox_metadata.py:62
#: ../pykolab/cli/cmd_set_mailbox_metadata.py:67
msgid "Metadata value"
msgstr ""

#: ../pykolab/cli/cmd_set_mailbox_metadata.py:61
#: ../pykolab/cli/cmd_set_mailbox_metadata.py:66
msgid "Metadata path"
msgstr ""

#: ../pykolab/cli/cmd_sync.py:41
#, python-format
msgid "Found %d domains in %d seconds"
msgstr ""

#: ../pykolab/cli/cmd_sync.py:51
#, python-format
msgid "Running for domain %s"
msgstr ""

#: ../pykolab/cli/cmd_sync.py:57
#, python-format
msgid "Synchronizing users for %s took %d seconds"
msgstr ""

#. This is a nested command
#. This is a nested component
#: ../pykolab/cli/commands.py:101 ../pykolab/setup/components.py:90
#, python-format
msgid "Command Group: %s"
msgstr ""

#: ../pykolab/cli/commands.py:116 ../pykolab/cli/commands.py:121
msgid "No such command."
msgstr ""

#: ../pykolab/cli/commands.py:171 ../pykolab/setup/components.py:231
#, python-format
msgid "Command '%s' already registered"
msgstr ""

#: ../pykolab/cli/commands.py:196 ../pykolab/setup/components.py:257
#: ../wallace/modules.py:348
#, python-format
msgid "Alias for %s"
msgstr ""

#: ../pykolab/cli/commands.py:204 ../pykolab/setup/components.py:265
msgid "Not yet implemented"
msgstr ""

#: ../pykolab/cli/telemetry/cmd_examine_command_issue.py:40
msgid "Unspecified command issue identifier"
msgstr ""

#: ../pykolab/cli/telemetry/cmd_examine_command_issue.py:50
msgid "Invalid command issue identifier"
msgstr ""

#: ../pykolab/cli/telemetry/cmd_examine_command_issue.py:60
#: ../pykolab/cli/telemetry/cmd_examine_session.py:65
msgid "Invalid session identifier"
msgstr ""

#: ../pykolab/cli/telemetry/cmd_examine_command_issue.py:75
#: ../pykolab/cli/telemetry/cmd_examine_session.py:100
#, python-format
msgid "Session by %s on server %s"
msgstr ""

#: ../pykolab/cli/telemetry/cmd_examine_session.py:43
msgid "Unspecified session identifier"
msgstr ""

#: ../pykolab/cli/telemetry/cmd_list_sessions.py:35
msgid "List Options"
msgstr ""

#: ../pykolab/cli/telemetry/cmd_list_sessions.py:40
msgid "Display sessions since ..."
msgstr ""

#: ../pykolab/cli/telemetry/cmd_list_sessions.py:58
#, python-format
msgid "Session for user %s started at %s with ID %s"
msgstr ""

#: ../pykolab/conf/entitlement.py:57 ../pykolab/conf/entitlement.py:80
#: ../pykolab/conf/entitlement.py:98 ../pykolab/conf/entitlement.py:116
#: ../pykolab/conf/entitlement.py:230 ../pykolab/conf/entitlement.py:246
#: ../pykolab/conf/entitlement.py:262
msgid "Invalid entitlement verification "
msgstr ""

#: ../pykolab/conf/entitlement.py:120 ../pykolab/conf/entitlement.py:123
msgid "Invalid entitlement certificate"
msgstr ""

#: ../pykolab/conf/entitlement.py:132
#, python-format
msgid "Parsing entitlement file %s"
msgstr ""

#: ../pykolab/conf/entitlement.py:141
#, python-format
msgid "License file %s not readable!"
msgstr ""

#: ../pykolab/conf/entitlement.py:147
msgid "No entitlement directory found"
msgstr ""

#: ../pykolab/conf/__init__.py:87
#, python-format
msgid "Setting %s to %r (from defaults)"
msgstr ""

#: ../pykolab/conf/__init__.py:106
#, python-format
msgid "Setting %s to %r (from CLI, verified)"
msgstr ""

#: ../pykolab/conf/__init__.py:109
#, python-format
msgid "Setting %s to %r (from CLI, not checked)"
msgstr ""

#: ../pykolab/conf/__init__.py:150 ../pykolab/conf/__init__.py:207
#, python-format
msgid "Setting %s_%s to '****' (from configuration file)"
msgstr ""

#: ../pykolab/conf/__init__.py:152 ../pykolab/conf/__init__.py:209
#, python-format
msgid "Setting %s_%s to %r (from configuration file)"
msgstr ""

#: ../pykolab/conf/__init__.py:162
msgid "Setting options from configuration file"
msgstr ""

#: ../pykolab/conf/__init__.py:223
#, python-format
msgid "Configuration file %s not readable"
msgstr ""

#: ../pykolab/conf/__init__.py:226
#, python-format
msgid "Reading configuration file %s"
msgstr ""

#: ../pykolab/conf/__init__.py:230
#, python-format
msgid "Invalid configuration file %s"
msgstr ""

#: ../pykolab/conf/__init__.py:233
#, python-format
msgid "No master configuration section [kolab] in configuration file %s"
msgstr ""

#. #
#. # Runtime Options
#. #
#: ../pykolab/conf/__init__.py:267
msgid "Runtime Options"
msgstr ""

#: ../pykolab/conf/__init__.py:272
msgid "Configuration file to use"
msgstr ""

#: ../pykolab/conf/__init__.py:278
msgid "Set the debugging "
msgstr ""

#: ../pykolab/conf/__init__.py:286
msgid "Set the logging level. "
msgstr ""

#: ../pykolab/conf/__init__.py:294
msgid "Log file to use"
msgstr ""

#: ../pykolab/conf/__init__.py:300
msgid "Be quiet."
msgstr ""

#: ../pykolab/conf/__init__.py:306
msgid "Answer yes to all questions."
msgstr ""

#: ../pykolab/conf/__init__.py:328
msgid "No command supplied"
msgstr ""

#: ../pykolab/conf/__init__.py:411
msgid "Insufficient options. Need section, key and value -in that order."
msgstr ""

#: ../pykolab/conf/__init__.py:414
#, python-format
msgid "No section '%s' exists."
msgstr ""

#: ../pykolab/conf/__init__.py:445
#, python-format
msgid "Setting %s to %r (from the default values for CLI options)"
msgstr ""

#: ../pykolab/conf/__init__.py:514
#, python-format
msgid "Could not execute configuration function: %s"
msgstr ""

#: ../pykolab/conf/__init__.py:522
#, python-format
msgid "Option %s/%s does not exist in config file %s, pulling from defaults"
msgstr ""

#: ../pykolab/conf/__init__.py:530 ../pykolab/conf/__init__.py:533
msgid "Option does not exist in defaults."
msgstr ""

#: ../pykolab/conf/__init__.py:543
#, python-format
msgid "Configuration file %s not readable."
msgstr ""

#: ../pykolab/conf/__init__.py:546
#, python-format
msgid "Configuration file %s does not exist."
msgstr ""

#: ../pykolab/conf/__init__.py:551
msgid ""
"WARNING: A negative debug level value does not make this program be any more "
"silent."
msgstr ""

#: ../pykolab/conf/__init__.py:557
msgid "This program has 9 levels of verbosity. Using the maximum of 9."
msgstr ""

#: ../pykolab/conf/__init__.py:565 ../pykolab/conf/__init__.py:571
msgid "Cannot start SASL authentication daemon"
msgstr ""

#: ../pykolab/conf/__init__.py:582
msgid "No imaplib library found."
msgstr ""

#: ../pykolab/conf/__init__.py:592
msgid "No LMTP class found in the smtplib library."
msgstr ""

#: ../pykolab/conf/__init__.py:602
msgid "No SMTP class found in the smtplib library."
msgstr ""

#: ../pykolab/conf/__init__.py:616
#, python-format
msgid "Found you specified a specific set of items to test: %s"
msgstr ""

#: ../pykolab/conf/__init__.py:624
#, python-format
msgid "Selectively selecting: %s"
msgstr ""

#: ../pykolab/constants.py.in:40
msgid "PyKolab is a Kolab Systems product. For more information "
msgstr ""

#: ../pykolab/constants.py.in:54
msgid "WARNING"
msgstr ""

#: ../pykolab/constants.py.in:54
msgid "The Fully Qualified "
msgstr ""

#: ../pykolab/constants.py.in:75
msgid "389 Directory Server or Red Hat Directory Server"
msgstr ""

#: ../pykolab/constants.py.in:79 ../pykolab/constants.py.in:83
msgid "OpenLDAP or compatible"
msgstr ""

#: ../pykolab/imap/cyrus.py:79
#, python-format
msgid "Could not connect to Cyrus IMAP server %r"
msgstr ""

#: ../pykolab/imap/cyrus.py:136
#, python-format
msgid "Continuing with separator: %r"
msgstr ""

#: ../pykolab/imap/cyrus.py:141
msgid "Detected we are running in a Murder topology"
msgstr ""

#: ../pykolab/imap/cyrus.py:145
msgid "This system is not part of a murder topology"
msgstr ""

#: ../pykolab/imap/cyrus.py:166
#, python-format
msgid "Checking actual backend server for folder %s through annotations"
msgstr ""

#: ../pykolab/imap/cyrus.py:181
#, python-format
msgid "Could not get the annotations after %s tries."
msgstr ""

#: ../pykolab/imap/cyrus.py:185
#, python-format
msgid "No annotations for %s: %r"
msgstr ""

#: ../pykolab/imap/cyrus.py:192
#, python-format
msgid "Server for INBOX folder %s is %s"
msgstr ""

#: ../pykolab/imap/cyrus.py:204
#, python-format
msgid "Setting quota for folder %s to %s"
msgstr ""

#: ../pykolab/imap/cyrus.py:208
#, python-format
msgid "Could not set quota for mailfolder %s"
msgstr ""

#: ../pykolab/imap/cyrus.py:217
#, python-format
msgid "Moving INBOX folder %s to %s"
msgstr ""

#: ../pykolab/imap/cyrus.py:232
#, python-format
msgid "Setting annotation %s on folder %s"
msgstr ""

#: ../pykolab/imap/cyrus.py:237
#, python-format
msgid "Could not set annotation %r on mail folder %r: %r"
msgstr ""

#: ../pykolab/imap/cyrus.py:241
#, python-format
msgid "Transferring folder %s from %s to %s"
msgstr ""

#: ../pykolab/imap/cyrus.py:301
#, python-format
msgid "Undeleting %s to %s"
msgstr ""

#: ../pykolab/imap/__init__.py:45
#, python-format
msgid "Cleaning up ACL entries for %s across all folders"
msgstr ""

#: ../pykolab/imap/__init__.py:60
#, python-format
msgid "Cleaning up ACL entries referring to identifier %s"
msgstr ""

#: ../pykolab/imap/__init__.py:69
#, python-format
msgid "Iterating over %d folders"
msgstr ""

#. Set the ACL to '' (effectively deleting the ACL entry)
#: ../pykolab/imap/__init__.py:82
#, python-format
msgid "Removing acl %r for subject %r from folder %r"
msgstr ""

#: ../pykolab/imap/__init__.py:143
#, python-format
msgid "Logging on to Cyrus IMAP server %s"
msgstr ""

#: ../pykolab/imap/__init__.py:152
#, python-format
msgid "Logging on to Dovecot IMAP server %s"
msgstr ""

#: ../pykolab/imap/__init__.py:161
#, python-format
msgid "Logging on to generic IMAP server %s"
msgstr ""

#: ../pykolab/imap/__init__.py:179
#, python-format
msgid "Reusing existing IMAP server connection to %s"
msgstr ""

#: ../pykolab/imap/__init__.py:181
#, python-format
msgid "Reconnecting to IMAP server %s"
msgstr ""

#: ../pykolab/imap/__init__.py:197
msgid "Called imap.disconnect() on a server that we had no connection to."
msgstr ""

#: ../pykolab/imap/__init__.py:212
#, python-format
msgid "%r has no attribute %s"
msgstr ""

#: ../pykolab/imap/__init__.py:279
msgid "Private annotations need to be set using the appropriate user account."
msgstr ""

#: ../pykolab/imap/__init__.py:294 ../pykolab/imap/__init__.py:329
#, python-format
msgid "Creating new shared folder %s"
msgstr ""

#: ../pykolab/imap/__init__.py:354 ../pykolab/imap/__init__.py:504
#, python-format
msgid "Downcasing mailbox name %r"
msgstr ""

#: ../pykolab/imap/__init__.py:358
#, python-format
msgid "Creating new mailbox for user %s"
msgstr ""

#: ../pykolab/imap/__init__.py:387
#, python-format
msgid "Creating additional folders for user %s"
msgstr ""

#: ../pykolab/imap/__init__.py:407
#, python-format
msgid "Mailbox already exists: %s"
msgstr ""

#: ../pykolab/imap/__init__.py:443
msgid "Subscribing user to the additional folders"
msgstr ""

#: ../pykolab/imap/__init__.py:458
#, python-format
msgid "Folder %s"
msgstr ""

#: ../pykolab/imap/__init__.py:470
#, python-format
msgid "Subscribing %s to folder %s"
msgstr ""

#: ../pykolab/imap/__init__.py:520 ../pykolab/imap/__init__.py:594
#, python-format
msgid "Renaming INBOX from %s to %s"
msgstr ""

#: ../pykolab/imap/__init__.py:524
#, python-format
msgid "Could not rename INBOX folder %s to %s"
msgstr ""

#: ../pykolab/imap/__init__.py:526 ../pykolab/imap/__init__.py:598
#, python-format
msgid "Moving INBOX folder %s won't succeed as target folder %s already exists"
msgstr ""

#: ../pykolab/imap/__init__.py:536
#, python-format
msgid "Looking for folder '%s', we found folders: %r"
msgstr ""

#: ../pykolab/imap/__init__.py:559
#, python-format
msgid "Setting ACL rights %s for subject %s on folder "
msgstr ""

#: ../pykolab/imap/__init__.py:570
#, python-format
msgid "Removing ACL rights %s for subject %s on folder "
msgstr ""

#: ../pykolab/imap/__init__.py:591
#, python-format
msgid "Found old INBOX folder %s"
msgstr ""

#: ../pykolab/imap/__init__.py:600
#, python-format
msgid "Did not find old folder user/%s to rename"
msgstr ""

#: ../pykolab/imap/__init__.py:602
msgid "Value for user is not a dictionary"
msgstr ""

#. TODO: Go in fact correct the quota.
#: ../pykolab/imap/__init__.py:662
#, python-format
msgid "Cannot get current IMAP quota for folder %s"
msgstr ""

#: ../pykolab/imap/__init__.py:675
#, python-format
msgid "Quota for %s currently is %s"
msgstr ""

#: ../pykolab/imap/__init__.py:681
#, python-format
msgid "Adjusting authentication database quota for folder %s to %d"
msgstr ""

#: ../pykolab/imap/__init__.py:686
#, python-format
msgid "Correcting quota for %s to %s (currently %s)"
msgstr ""

#: ../pykolab/imap/__init__.py:763
#, python-format
msgid "Checking folder: %s"
msgstr ""

#: ../pykolab/imap/__init__.py:768
#, python-format
msgid "Folder has no corresponding user (1): %s"
msgstr ""

#: ../pykolab/imap/__init__.py:771
#, python-format
msgid "Folder has no corresponding user (2): %s"
msgstr ""

#. We got user identifier only
#: ../pykolab/imap/__init__.py:786
msgid "Please don't give us just a user identifier"
msgstr ""

#: ../pykolab/imap/__init__.py:789
#, python-format
msgid "Deleting folder %s"
msgstr ""

#: ../pykolab/__init__.py:50
msgid "Returning thread local configuration"
msgstr ""

#: ../pykolab/logger.py:106
#, python-format
msgid "Could not change the ownership of log file %s"
msgstr ""

#: ../pykolab/logger.py:122
#, python-format
msgid "Cannot log to file %s: %s"
msgstr ""

#: ../pykolab/plugins/defaultfolders/__init__.py:47
#, python-format
msgid "Plugin %s called without required keyword %s."
msgstr ""

#: ../pykolab/plugins/defaultfolders/__init__.py:53
msgid "Could not parse additional_folders"
msgstr ""

#: ../pykolab/plugins/dynamicquota/__init__.py:58
#, python-format
msgid "No keyword %s passed to set_user_folder_quota"
msgstr ""

#: ../pykolab/plugins/dynamicquota/__init__.py:70
#, python-format
msgid "Quota '%s' not an integer!"
msgstr ""

#: ../pykolab/plugins/__init__.py:70
#, python-format
msgid "ImportError for plugin %s: %s"
msgstr ""

#: ../pykolab/plugins/__init__.py:74
#, python-format
msgid "RuntimeError for plugin %s: %s"
msgstr ""

#: ../pykolab/plugins/__init__.py:78
#, python-format
msgid "Plugin %s failed to load (%s: %s)"
msgstr ""

#: ../pykolab/plugins/__init__.py:116 ../pykolab/plugins/__init__.py:118
#, python-format
msgid "Cannot set defaults for plugin %s: %s"
msgstr ""

#: ../pykolab/plugins/__init__.py:120
#, python-format
msgid "Cannot set defaults for plugin %s: Unknown Error"
msgstr ""

#: ../pykolab/plugins/__init__.py:123
#, python-format
msgid "Not setting defaults for plugin %s: No function 'set_defaults()'"
msgstr ""

#: ../pykolab/plugins/__init__.py:142
#, python-format
msgid "Cannot set runtime for plugin %s: %s"
msgstr ""

#: ../pykolab/plugins/__init__.py:144
#, python-format
msgid "Not setting runtime for plugin %s: No function 'set_runtime()'"
msgstr ""

#: ../pykolab/plugins/__init__.py:163 ../pykolab/plugins/__init__.py:165
#, python-format
msgid "Cannot add options for plugin %s: %s"
msgstr ""

#: ../pykolab/plugins/__init__.py:167
#, python-format
msgid "Not adding options for plugin %s: No function 'add_options()'"
msgstr ""

#: ../pykolab/plugins/__init__.py:187
#, python-format
msgid "Cannot check options for plugin %s: %s"
msgstr ""

#: ../pykolab/plugins/__init__.py:189
#, python-format
msgid "Not checking options for plugin %s: No function 'check_options()'"
msgstr ""

#: ../pykolab/plugins/__init__.py:227
#, python-format
msgid "Executing hook %s for plugin %s"
msgstr ""

#: ../pykolab/plugins/__init__.py:231 ../pykolab/plugins/__init__.py:233
#, python-format
msgid "Cannot execute hook %s for plugin %s: %s"
msgstr ""

#: ../pykolab/plugins/recipientpolicy/__init__.py:79
msgid "Attribute substitution for 'mail' failed in Recipient Policy"
msgstr ""

#: ../pykolab/plugins/recipientpolicy/__init__.py:115
msgid "Could not parse the alternative mail routines"
msgstr ""

#: ../pykolab/plugins/recipientpolicy/__init__.py:119
#, python-format
msgid "Alternative mail routines: %r"
msgstr ""

#: ../pykolab/plugins/recipientpolicy/__init__.py:130
#: ../pykolab/plugins/recipientpolicy/__init__.py:141
#, python-format
msgid "Appending additional mail address: %s"
msgstr ""

#: ../pykolab/plugins/recipientpolicy/__init__.py:134
#: ../pykolab/plugins/recipientpolicy/__init__.py:145
msgid ""
"Attribute substitution for 'alternative_mail' failed in Recipient Policy"
msgstr ""

#: ../pykolab/setup/components.py:58
msgid "Display this help."
msgstr ""

#: ../pykolab/setup/components.py:149
msgid "No component selected, continuing for all components"
msgstr ""

#: ../pykolab/setup/components.py:187 ../pykolab/setup/components.py:192
msgid "No such component."
msgstr ""

#: ../pykolab/setup/setup_freebusy.py:46
msgid "Setup Free/Busy."
msgstr ""

#: ../pykolab/setup/setup_freebusy.py:50
msgid "Free/Busy is not installed on this system"
msgstr ""

#: ../pykolab/setup/setup_freebusy.py:55
msgid ""
"\n"
"                        Please supply the MySQL password for the "
"'roundcube'\n"
"                        user. You have supplied this password earlier, and "
"it is\n"
"                        available from the database URI setting in\n"
"                        /etc/roundcubemail/db.inc.php.\n"
"                    "
msgstr ""

#: ../pykolab/setup/setup_freebusy.py:64
#: ../pykolab/setup/setup_roundcube.py:56
msgid "MySQL roundcube password"
msgstr ""

#: ../pykolab/setup/setup_freebusy.py:92
#: ../pykolab/setup/setup_roundcube.py:115 ../pykolab/setup/setup_zpush.py:71
#, python-format
msgid "Using template file %r"
msgstr ""

#: ../pykolab/setup/setup_freebusy.py:99
#: ../pykolab/setup/setup_roundcube.py:122 ../pykolab/setup/setup_zpush.py:78
#, python-format
msgid "Successfully compiled template %r, writing out to %r"
msgstr ""

#: ../pykolab/setup/setup_freebusy.py:119
#: ../pykolab/setup/setup_roundcube.py:193
#: ../pykolab/setup/setup_syncroton.py:66 ../pykolab/setup/setup_zpush.py:98
msgid "Could not start the webserver server service."
msgstr ""

#: ../pykolab/setup/setup_freebusy.py:128 ../pykolab/setup/setup_imap.py:169
#: ../pykolab/setup/setup_kolabd.py:81 ../pykolab/setup/setup_ldap.py:327
#: ../pykolab/setup/setup_mta.py:378 ../pykolab/setup/setup_mysql.py:58
#: ../pykolab/setup/setup_roundcube.py:202
#: ../pykolab/setup/setup_syncroton.py:75 ../pykolab/setup/setup_zpush.py:107
msgid "Could not configure to start on boot, the "
msgstr ""

#: ../pykolab/setup/setup_imap.py:45
msgid "Setup IMAP."
msgstr ""

#: ../pykolab/setup/setup_imap.py:89 ../pykolab/setup/setup_imap.py:114
msgid "Could not write out Cyrus IMAP configuration file /etc/imapd.conf"
msgstr ""

#: ../pykolab/setup/setup_imap.py:154
msgid "Could not start the cyrus-imapd and kolab-saslauthd services."
msgstr ""

#: ../pykolab/setup/setup_kolabd.py:43
msgid "Setup the Kolab daemon."
msgstr ""

#: ../pykolab/setup/setup_kolabd.py:51
#, python-format
msgid ""
"\n"
"                            Copying the configuration section for 'example."
"org' over to\n"
"                            a section applicable to your domain '%s'.\n"
"                        "
msgstr ""

#: ../pykolab/setup/setup_kolabd.py:72
msgid "Could not start the kolab server service."
msgstr ""

#: ../pykolab/setup/setup_ldap.py:45
msgid "LDAP Options"
msgstr ""

#: ../pykolab/setup/setup_ldap.py:52
msgid "Specify FQDN (overriding defaults)."
msgstr ""

#: ../pykolab/setup/setup_ldap.py:60
msgid "Allow anonymous binds (default: no)."
msgstr ""

#: ../pykolab/setup/setup_ldap.py:64
msgid "Setup LDAP."
msgstr ""

#: ../pykolab/setup/setup_ldap.py:76
msgid ""
"\n"
"                        Please supply a password for the LDAP administrator "
"user\n"
"                        'admin', used to login to the graphical console of "
"389\n"
"                        Directory server.\n"
"                    "
msgstr ""

#: ../pykolab/setup/setup_ldap.py:84
msgid "Administrator password"
msgstr ""

#: ../pykolab/setup/setup_ldap.py:91
msgid ""
"\n"
"                        Please supply a password for the LDAP Directory "
"Manager\n"
"                        user, which is the administrator user you will be "
"using\n"
"                        to at least initially log in to the Web Admin, and "
"that\n"
"                        Kolab uses to perform administrative tasks.\n"
"                    "
msgstr ""

#: ../pykolab/setup/setup_ldap.py:100
msgid "Directory Manager password"
msgstr ""

#: ../pykolab/setup/setup_ldap.py:107
msgid ""
"\n"
"                        Please choose the system user and group the service\n"
"                        should use to run under. These should be existing,\n"
"                        unprivileged, local system POSIX accounts with no "
"shell.\n"
"                    "
msgstr ""

#: ../pykolab/setup/setup_ldap.py:117 ../pykolab/setup/setup_ldap.py:120
msgid "User"
msgstr ""

#: ../pykolab/setup/setup_ldap.py:118 ../pykolab/setup/setup_ldap.py:121
msgid "Group"
msgstr ""

#: ../pykolab/setup/setup_ldap.py:157
msgid ""
"\n"
"                        This setup procedure plans to set up Kolab Groupware "
"for\n"
"                        the following domain name space. This domain name "
"is\n"
"                        obtained from the reverse DNS entry on your network\n"
"                        interface. Please confirm this is the appropriate "
"domain\n"
"                        name space.\n"
"                    "
msgstr ""

#: ../pykolab/setup/setup_ldap.py:171
msgid "Domain name to use"
msgstr ""

#: ../pykolab/setup/setup_ldap.py:176 ../pykolab/setup/setup_ldap.py:201
msgid ""
"\n"
"                                    Invalid input. Please try again.\n"
"                                "
msgstr ""

#: ../pykolab/setup/setup_ldap.py:185
msgid ""
"\n"
"                        The standard root dn we composed for you follows. "
"Please\n"
"                        confirm this is the root dn you wish to use.\n"
"                    "
msgstr ""

#: ../pykolab/setup/setup_ldap.py:196
msgid "Root DN to use"
msgstr ""

#: ../pykolab/setup/setup_ldap.py:244
msgid "No directory server setup tool available."
msgstr ""

#: ../pykolab/setup/setup_ldap.py:255
msgid ""
"\n"
"                    Setup is now going to set up the 389 Directory Server. "
"This\n"
"                    may take a little while (during which period there is "
"no\n"
"                    output and no progress indication).\n"
"                "
msgstr ""

#: ../pykolab/setup/setup_ldap.py:262
msgid "Setting up 389 Directory Server"
msgstr ""

#. TODO: Get the return code and display output if not successful.
#: ../pykolab/setup/setup_ldap.py:274
msgid "Setup DS stdout:"
msgstr ""

#: ../pykolab/setup/setup_ldap.py:277
msgid "Setup DS stderr:"
msgstr ""

#: ../pykolab/setup/setup_ldap.py:303
msgid "Could not copy the LDAP extensions for Kolab"
msgstr ""

#: ../pykolab/setup/setup_ldap.py:306
msgid "Could not find the ldap Kolab schema file"
msgstr ""

#: ../pykolab/setup/setup_ldap.py:318
msgid "Could not start the directory server service."
msgstr ""

#: ../pykolab/setup/setup_ldap.py:332
msgid ""
"\n"
"                        Please supply a Cyrus Administrator password. This\n"
"                        password is used by Kolab to execute administrative\n"
"                        tasks in Cyrus IMAP. You may also need the password\n"
"                        yourself to troubleshoot Cyrus IMAP and/or perform\n"
"                        other administrative tasks against Cyrus IMAP "
"directly.\n"
"                    "
msgstr ""

#: ../pykolab/setup/setup_ldap.py:342
msgid "Cyrus Administrator password"
msgstr ""

#: ../pykolab/setup/setup_ldap.py:349
msgid ""
"\n"
"                        Please supply a Kolab Service account password. "
"This\n"
"                        account is used by various services such as "
"Postfix,\n"
"                        and Roundcube, as anonymous binds to the LDAP "
"server\n"
"                        will not be allowed.\n"
"                    "
msgstr ""

#: ../pykolab/setup/setup_ldap.py:358
msgid "Kolab Service password"
msgstr ""

#: ../pykolab/setup/setup_ldap.py:368
msgid "Writing out configuration to kolab.conf"
msgstr ""

#: ../pykolab/setup/setup_ldap.py:382
msgid "Inserting service users into LDAP."
msgstr ""

#: ../pykolab/setup/setup_ldap.py:456
msgid "Writing out cn=kolab,cn=config"
msgstr ""

#. TODO: Add kolab-admin role
#. TODO: Assign kolab-admin admin ACLs
#: ../pykolab/setup/setup_ldap.py:480
#, python-format
msgid "Adding domain %s to list of domains for this deployment"
msgstr ""

#: ../pykolab/setup/setup_ldap.py:497
msgid "Disabling anonymous binds"
msgstr ""

#. TODO: Ensure the uid attribute is unique
#. TODO^2: Consider renaming the general "attribute uniqueness to "uid attribute uniqueness"
#: ../pykolab/setup/setup_ldap.py:505
msgid "Enabling attribute uniqueness plugin"
msgstr ""

#: ../pykolab/setup/setup_ldap.py:511
msgid "Enabling referential integrity plugin"
msgstr ""

#: ../pykolab/setup/setup_ldap.py:517
msgid "Enabling and configuring account policy plugin"
msgstr ""

#. TODO: Add kolab-admin role
#: ../pykolab/setup/setup_ldap.py:532
msgid "Adding the kolab-admin role"
msgstr ""

#. TODO: User writeable attributes on root_dn
#: ../pykolab/setup/setup_ldap.py:543
#, python-format
msgid "Setting access control to %s"
msgstr ""

#: ../pykolab/setup/setup_ldap.py:568
msgid "Could not start and configure to start on boot, the "
msgstr ""

#: ../pykolab/setup/setup_mta.py:41
msgid "Setup MTA."
msgstr ""

#: ../pykolab/setup/setup_mta.py:245 ../pykolab/setup/setup_php.py:104
#, python-format
msgid "Setting key %r to %r"
msgstr ""

#: ../pykolab/setup/setup_mta.py:278
msgid "Could not write out Postfix configuration file /etc/postfix/master.cf"
msgstr ""

#: ../pykolab/setup/setup_mta.py:321
msgid "Could not write out Amavis configuration file /etc/amavisd/amavisd.conf"
msgstr ""

#: ../pykolab/setup/setup_mta.py:329
msgid "Not writing out any configuration for Amavis."
msgstr ""

#: ../pykolab/setup/setup_mta.py:360
msgid "Could not start the postfix, clamav and amavisd services services."
msgstr ""

#: ../pykolab/setup/setup_mysql.py:39
msgid "Setup MySQL."
msgstr ""

#: ../pykolab/setup/setup_mysql.py:49
msgid "Could not start the MySQL database service."
msgstr ""

#: ../pykolab/setup/setup_mysql.py:68
msgid "What MySQL server are we setting up?"
msgstr ""

#: ../pykolab/setup/setup_mysql.py:72
msgid ""
"\n"
"                        Please supply the root password for MySQL, so we can "
"set\n"
"                        up user accounts for other components that use "
"MySQL.\n"
"                    "
msgstr ""

#: ../pykolab/setup/setup_mysql.py:79 ../pykolab/setup/setup_mysql.py:96
msgid "MySQL root password"
msgstr ""

#: ../pykolab/setup/setup_mysql.py:85
msgid ""
"\n"
"                        Please supply a root password for MySQL. This "
"password\n"
"                        will be the administrative user for this MySQL "
"server,\n"
"                        and it should be kept a secret. After this setup "
"process\n"
"                        has completed, Kolab is going to discard and forget\n"
"                        about this password, but you will need it for\n"
"                        administrative tasks in MySQL.\n"
"                    "
msgstr ""

#: ../pykolab/setup/setup_mysql.py:136
msgid ""
"\n"
"                        Please supply a password for the MySQL user "
"'kolab'.\n"
"                        This password will be used by Kolab services, such "
"as\n"
"                        the Web Administration Panel.\n"
"                    "
msgstr ""

#: ../pykolab/setup/setup_mysql.py:144
msgid "MySQL kolab password"
msgstr ""

#: ../pykolab/setup/setup_mysql.py:162
msgid "Could not find the MySQL Kolab schema file"
msgstr ""

#: ../pykolab/setup/setup_php.py:42
msgid "PHP Options"
msgstr ""

#: ../pykolab/setup/setup_php.py:49
msgid "Specify the timezone for PHP."
msgstr ""

#: ../pykolab/setup/setup_php.py:57
msgid "Specify the path to the php.ini file used with the webserver."
msgstr ""

#: ../pykolab/setup/setup_php.py:61
msgid "Setup PHP."
msgstr ""

#: ../pykolab/setup/setup_php.py:66
msgid ""
"\n"
"                        Please supply the timezone PHP should be using.\n"
"                    "
msgstr ""

#: ../pykolab/setup/setup_php.py:72
msgid "Timezone ID"
msgstr ""

#: ../pykolab/setup/setup_php.py:78
#, python-format
msgid "Cannot configure PHP through %r (No such file or directory)"
msgstr ""

#: ../pykolab/setup/setup_php.py:89
msgid "Could not find PHP configuration file php.ini"
msgstr ""

#: ../pykolab/setup/setup_roundcube.py:44
msgid "Setup Roundcube."
msgstr ""

#: ../pykolab/setup/setup_roundcube.py:48
msgid ""
"\n"
"                    Please supply a password for the MySQL user "
"'roundcube'.\n"
"                    This password will be used by the Roundcube webmail\n"
"                    interface.\n"
"                "
msgstr ""

#: ../pykolab/setup/setup_syncroton.py:40
msgid "Setup Syncroton."
msgstr ""

#: ../pykolab/setup/setup_zpush.py:41
msgid "Setup zpush."
msgstr ""

#: ../pykolab/setup/setup_zpush.py:45
msgid "Z-Push is not installed on this system"
msgstr ""

#. start_max = (int)(time.time())
#: ../pykolab/telemetry.py:588
#, python-format
msgid "Expiring sessions that started before or on %d"
msgstr ""

#: ../pykolab/telemetry.py:601
#, python-format
msgid "Expiring session ID: %d"
msgstr ""

#: ../pykolab/telemetry.py:620
#, python-format
msgid "Session with ID %d expired from database"
msgstr ""

#: ../pykolab/telemetry.py:646
#, python-format
msgid "Operational Error in telemetry database: %s"
msgstr ""

#: ../pykolab/telemetry.py:652
msgid "No database available"
msgstr ""

#: ../pykolab/utils.py:60 ../pykolab/utils.py:62
#, python-format
msgid "Confirm %s: "
msgstr ""

#: ../pykolab/utils.py:65
msgid "Incorrect confirmation. "
msgstr ""

#: ../pykolab/utils.py:70 ../pykolab/utils.py:75
#, python-format
msgid "%s: "
msgstr ""

#: ../pykolab/utils.py:72 ../pykolab/utils.py:77
#, python-format
msgid "%s [%s]: "
msgstr ""

#: ../pykolab/utils.py:122
msgid "Please answer 'yes' or 'no'."
msgstr ""

#: ../pykolab/utils.py:148
msgid "Choice"
msgstr ""

#: ../pykolab/utils.py:214
#, python-format
msgid "Could not change the permissions on %s"
msgstr ""

#: ../pykolab/utils.py:395
#, python-format
msgid "Transliterating string %r with locale %r"
msgstr ""

#: ../pykolab/utils.py:403
msgid "Attempting to set locale"
msgstr ""

#: ../pykolab/utils.py:405
msgid "Success setting locale"
msgstr ""

#: ../pykolab/utils.py:407
msgid "Failure to set locale"
msgstr ""

#: ../pykolab/utils.py:415
#, python-format
msgid "Executing '%s | %s'"
msgstr ""

#: ../pykolab/wap_client/__init__.py:257
#, python-format
msgid "Requesting %r with params %r"
msgstr ""

#: ../pykolab/wap_client/__init__.py:263
#, python-format
msgid "Got response: %r"
msgstr ""

#. Some data is not JSON
#: ../pykolab/wap_client/__init__.py:268
msgid "Response data is not JSON"
msgstr ""

#: ../pykolab/xml/attendee.py:79 ../pykolab/xml/attendee.py:99
msgid "Not a valid attendee"
msgstr ""

#: ../pykolab/xml/attendee.py:84
msgid "No valid delegator references found"
msgstr ""

#: ../pykolab/xml/attendee.py:104
msgid "No valid delegatee references found"
msgstr ""

#: ../pykolab/xml/attendee.py:140
#, python-format
msgid "Invalid cutype %r"
msgstr ""

#: ../pykolab/xml/attendee.py:151
#, python-format
msgid "Invalid participant status %r"
msgstr ""

#: ../pykolab/xml/attendee.py:159
#, python-format
msgid "Invalid role %r"
msgstr ""

#: ../pykolab/xml/event.py:172
#, python-format
msgid "No attendee with email or name %r"
msgstr ""

#: ../pykolab/xml/event.py:180
#, python-format
msgid "Invalid argument value attendee %r, must be basestring or Attendee"
msgstr ""

#: ../pykolab/xml/event.py:186
#, python-format
msgid "No attendee with email %r"
msgstr ""

#: ../pykolab/xml/event.py:192
#, python-format
msgid "No attendee with name %r"
msgstr ""

#: ../pykolab/xml/event.py:338
msgid "Invalid participant status"
msgstr ""

#: ../pykolab/xml/event.py:538
msgid "Event end needs datetime.date or datetime.datetime instance"
msgstr ""

#: ../pykolab/xml/event.py:657
#, python-format
msgid "Invalid status %r"
msgstr ""

#: ../pykolab/xml/event.py:678 ../pykolab/xml/event.py:728
msgid "Event start needs datetime.date or datetime.datetime instance"
msgstr ""

#: ../pykolab/xml/event.py:764
#, python-format
msgid "Invalid status set: %r"
msgstr ""

#: ../pykolab/xml/event.py:882
msgid "No sender specified"
msgstr ""

#: ../saslauthd/__init__.py:126 ../saslauthd/__init__.py:134
msgid "Traceback occurred, please report a bug at http://bugzilla.kolabsys.com"
msgstr ""

#: ../wallace/__init__.py:62
#, python-format
msgid "Worker process %s initializing"
msgstr ""

#: ../wallace/__init__.py:81
msgid "Bind address for Wallace."
msgstr ""

#: ../wallace/__init__.py:107
msgid "Port that Wallace is supposed to use."
msgstr ""

#: ../wallace/__init__.py:158
#, python-format
msgid "Could not bind to socket on port %d on bind "
msgstr ""

#: ../wallace/__init__.py:170
msgid "Could not shut down socket"
msgstr ""

#: ../wallace/__init__.py:227
msgid "Accepted connection"
msgstr ""

#: ../wallace/__init__.py:398
#, python-format
msgid "Could not write pid file %s"
msgstr ""

#: ../wallace/module_optout.py:61 ../wallace/module_resources.py:93
#, python-format
msgid "Issuing callback after processing to stage %s"
msgstr ""

#: ../wallace/module_optout.py:62 ../wallace/module_resources.py:99
#, python-format
msgid "Testing cb_action_%s()"
msgstr ""

#: ../wallace/module_optout.py:64 ../wallace/module_resources.py:102
#, python-format
msgid "Attempting to execute cb_action_%s()"
msgstr ""

#. modules.next_module('optout')
#: ../wallace/module_optout.py:70
#, python-format
msgid "Consulting opt-out service for %r, %r"
msgstr ""

#: ../wallace/module_optout.py:96
#, python-format
msgid "Running opt-out consult from envelope sender '%s "
msgstr ""

#: ../wallace/module_optout.py:160
#, python-format
msgid "Attempting to execute cb_action_%s(%r, %r)"
msgstr ""

#: ../wallace/module_optout.py:181
#, python-format
msgid "Could not send request to optout_url %s"
msgstr ""

#: ../wallace/module_resources.py:80
#, python-format
msgid "Resource Management called for %r, %r"
msgstr ""

#: ../wallace/module_resources.py:143
msgid "Message is not an iTip message or does not contain any "
msgstr ""

#: ../wallace/module_resources.py:151
msgid "iTip events attached to this message contain the "
msgstr ""

#: ../wallace/module_resources.py:171
msgid "Not an iTip message, but sent to resource nonetheless. Reject message"
msgstr ""

#: ../wallace/module_resources.py:179
msgid "No itips, no resources, pass along"
msgstr ""

#: ../wallace/module_resources.py:183
msgid "iTips, but no resources, pass along"
msgstr ""

#: ../wallace/module_resources.py:215
#, python-format
msgid "Resources: %r"
msgstr ""

#: ../wallace/module_resources.py:233
#, python-format
msgid "Checking events in resource folder %r"
msgstr ""

#: ../wallace/module_resources.py:240
#, python-format
msgid "Mailbox for resource %r doesn't exist"
msgstr ""

#: ../wallace/module_resources.py:253
#, python-format
msgid "Fetching message UID %r from folder %r"
msgstr ""

#: ../wallace/module_resources.py:292
#, python-format
msgid "Event %r conflicts with event "
msgstr ""

#: ../wallace/module_resources.py:305
#, python-format
msgid "start: %r, end: %r, total: %r, messages: %r"
msgstr ""

#: ../wallace/module_resources.py:312
#, python-format
msgid "Polling for resource %r"
msgstr ""

#: ../wallace/module_resources.py:316
#, python-format
msgid "Resource %r has been popped from the list"
msgstr ""

#: ../wallace/module_resources.py:323
msgid "Resource is a collection"
msgstr ""

#: ../wallace/module_resources.py:371 ../wallace/module_resources.py:421
#, python-format
msgid "Adding event to %r"
msgstr ""

#: ../wallace/module_resources.py:470
#, python-format
msgid "Method %r not really interesting for us."
msgstr ""

#: ../wallace/module_resources.py:478
#, python-format
msgid "Raw iTip payload: %s"
msgstr ""

#: ../wallace/module_resources.py:488
msgid "Could not read iTip from message."
msgstr ""

#: ../wallace/module_resources.py:510
msgid "iTip event without a start"
msgstr ""

#. end if c.name == "VEVENT"
#. end for c in cal.walk()
#. end if part.get_content_type() == "text/calendar"
#. end for part in message.walk()
#. if message.is_multipart()
#: ../wallace/module_resources.py:540
msgid "Message is not an iTip message (non-multipart message)"
msgstr ""

#: ../wallace/module_resources.py:561
#, python-format
msgid "Checking if email address %r belongs to a resource (collection)"
msgstr ""

#: ../wallace/module_resources.py:572 ../wallace/module_resources.py:646
#: ../wallace/module_resources.py:696
#, python-format
msgid "No resource (collection) records found for %r"
msgstr ""

#: ../wallace/module_resources.py:580 ../wallace/module_resources.py:654
#: ../wallace/module_resources.py:704
#, python-format
msgid "Resource record(s): %r"
msgstr ""

#: ../wallace/module_resources.py:586 ../wallace/module_resources.py:661
#: ../wallace/module_resources.py:711
#, python-format
msgid "Resource record: %r"
msgstr ""

#: ../wallace/module_resources.py:605
#, python-format
msgid "Raw itip_events: %r"
msgstr ""

#: ../wallace/module_resources.py:613
#, python-format
msgid "Raw set of attendees: %r"
msgstr ""

#: ../wallace/module_resources.py:621
#, python-format
msgid "Raw set of resources: %r"
msgstr ""

#: ../wallace/module_resources.py:635
#, python-format
msgid "Checking if attendee %r is a resource (collection)"
msgstr ""

#: ../wallace/module_resources.py:668 ../wallace/module_resources.py:714
msgid "Resource reservation made but no resource records found"
msgstr ""

#: ../wallace/module_resources.py:686
#, python-format
msgid "Checking if resource %r is a resource (collection)"
msgstr ""

#: ../wallace/module_resources.py:718
msgid "The following resources are being referred to in the "
msgstr ""

#. This is a nested module
#: ../wallace/modules.py:97
#, python-format
msgid "Module Group: %s"
msgstr ""

#: ../wallace/modules.py:108 ../wallace/modules.py:113
msgid "No such module."
msgstr ""

#: ../wallace/modules.py:119
#, python-format
msgid "Holding message in queue for manual review (%s by %s)"
msgstr ""

#: ../wallace/modules.py:122
#, python-format
msgid "Deferring message in %s (by module %s)"
msgstr ""

#: ../wallace/modules.py:133
#, python-format
msgid "The time when the message was sent: %r"
msgstr ""

#: ../wallace/modules.py:134
#, python-format
msgid "The time now: %r"
msgstr ""

#: ../wallace/modules.py:135
#, python-format
msgid "The time delta: %r"
msgstr ""

#. TODO: Send NDR back to user
#: ../wallace/modules.py:139
#, python-format
msgid "Message in file %s older then 5 days, deleting"
msgstr ""

#: ../wallace/modules.py:164
#, python-format
msgid "Rejecting message in %s (by module %s)"
msgstr ""

#: ../wallace/modules.py:185
#, python-format
msgid ""
"This is the email system Wallace at %s.\n"
"\n"
"I'm sorry to inform you we could not deliver the attached message\n"
"to the following recipients:\n"
"\n"
"- %s\n"
"\n"
"Your message is being delivered to any other recipients you may have\n"
"sent your message to. There is no need to resend the message to those\n"
"recipients.\n"
msgstr ""

#: ../wallace/modules.py:200
#, python-format
msgid ""
"X-Wallace-Module: %s\n"
"X-Wallace-Result: REJECT\n"
msgstr ""

#: ../wallace/modules.py:253
#, python-format
msgid "Accepting message in %s (by module %s)"
msgstr ""

#: ../wallace/modules.py:326
#, python-format
msgid "Module '%s' already registered"
msgstr ""
